/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


//#include<stdio.h>
#include<stdint.h>

/* This function executes in THREAD MODE */
void generate_RTC_WKUP_interrupt()
{
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	*pISER0 |= (1 << 3);	//enable IRQ3 interrupt
	*pSTIR = (3 & 0x1FF);	//generate an interrupt from software for IRQ3
}

/* This function executes in THREAD MODE */
int main(void)
{
	generate_RTC_WKUP_interrupt();
	for(;;);
}

/* This (ISR) interrupt-function executes in HANDLER MODE */
void RTC_WKUP_IRQHandler(void)
{
	asm("nop"); // Assembly instruction which does nothing
}

